"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

const FAQS = [
  {
    q: "Is NutriMind AI actually free to use?",
    a: "Yes. The Free plan is genuinely useful — 1 AI meal plan per month, basic tracking, and 5 fridge scans. No credit card required to sign up.",
  },
  {
    q: "How accurate is the AI meal planning?",
    a: "Meal plans are generated by Google Gemini with nutritional constraints calculated from your profile (TDEE, macro splits, allergies). Accuracy improves as you provide feedback on meals you like or dislike.",
  },
  {
    q: "What happens when I scan my fridge?",
    a: "You upload a photo. Our Gemini Vision integration identifies all visible ingredients, then generates 3–5 meals you can make right now with those ingredients — including full nutritional info.",
  },
  {
    q: "Can I connect a fitness tracker or wearable?",
    a: "Direct wearable sync is on the roadmap. Currently, you can manually input workout calorie burns which adjusts your daily targets automatically.",
  },
  {
    q: "Is my nutrition data private?",
    a: "Your data is stored securely with Supabase (row-level security). We never sell personal health data. You can export or delete your data at any time from Settings.",
  },
  {
    q: "Can I cancel my Pro subscription any time?",
    a: "Absolutely. Cancel from the Settings page with one click. You keep Pro features until the end of your billing period, then revert to Free — no data loss.",
  },
];

export function FAQSection() {
  const [open, setOpen] = useState<number | null>(null);

  return (
    <section id="faq" className="py-24 px-4 bg-muted/20">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-12">
          <h2
            className="text-4xl font-bold tracking-tight"
            style={{ fontFamily: "var(--font-display)" }}
          >
            Frequently asked questions
          </h2>
          <p className="mt-3 text-muted-foreground">
            Still have questions?{" "}
            <a href="mailto:support@nutrimind.ai" className="text-primary hover:underline">
              Contact us
            </a>
          </p>
        </div>

        <div className="space-y-2">
          {FAQS.map((faq, i) => (
            <div
              key={i}
              className="rounded-xl border border-border bg-card overflow-hidden"
            >
              <button
                className="w-full flex items-center justify-between p-5 text-left hover:bg-muted/30 transition-colors"
                onClick={() => setOpen(open === i ? null : i)}
              >
                <span className="font-medium text-sm leading-relaxed pr-4">
                  {faq.q}
                </span>
                <ChevronDown
                  className={cn(
                    "h-4 w-4 text-muted-foreground shrink-0 transition-transform duration-200",
                    open === i && "rotate-180"
                  )}
                />
              </button>
              {open === i && (
                <div className="px-5 pb-5 text-sm text-muted-foreground leading-relaxed animate-fade-up">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
